version: "3.7"

services:
  web:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: local.Dockerfile
    restart: always
    command: python run.py
    volumes:
      - ./:/app/
    ports:
      - 9000:9000
  db:
    env_file:
      - .env
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db/
  redis:
    env_file:
      - .env
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
  redis-insights:
    image: redislabs/redisinsight
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - redis

volumes:
  mongodb_data:
