version: "3.7"

services:
  web:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: local.Dockerfile
    restart: always
    command: python run.py
    volumes:
      - ./:/app/
    ports:
      - 9000:9000
  db:
    env_file:
      - .env
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db/

volumes:
  mongodb_data:
