[tool.pytest.ini_options]
addopts = "--maxfail=1 -rf"
norecursedirs = ["venv", "mongodb"]
testpaths = ["apps", "bases"]
python_files = ["test*.py"]
python_functions = ["*_test", "test_*"]
console_output_style = "progress"

[tool.coverage.run]
branch = true
omit = ["*/.local/*", "*/.idea/*", "*./venv/*", "*test*", "*__init__*", "*run.py"]

[tool.coverage.report]
# show_missing = true
ignore_errors = true
sort = "Cover"
precision = 4
omit = ["*/.local/*", "*/.idea/*", "*./venv/*", "*test*", "*__init__*", "*run.py"]
exclude_lines = ["pragma: no cover", "def __repr__", "if __name__ = .__main__.:"]

[tool.coverage.html]
directory = "coverage_html_report"

[tool.black]
line-length = 120

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120

[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.pylint.format]
max-line-length = "120"
